### ISSUE TITLE
Genderbendering our persons

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#101]
Our enlightened database does not know about the gender of the persons under its benevolent dictatorship. I fear that researchers, however, might be interested in such outdated concepts. Are there any reasons to not include this information in the persons table?

**Comment by inamoto4** [comment]
We are on it.

**Comment by duncdrum** [comment]
@inamoto4 issues should be close when the necessary changes are in the master branch. There is no need for manual intervention, use commit messages, or the comments field for pull-request.

**Comment by LenaHenningsen** [comment]
as long as we stick to only the two categories male/female.
Even though our readership, enlightened or otherwise dictatorial, may consider that insufficient

**Comment by duncdrum** [comment]
correct, but not a problem for the final app since the xml data models have more gender types. As long as we have the majority types in the csv data-model we are good.

**Comment by LenaHenningsen** [comment]
Well, I think during the 1970s people had more pressing problems than debating their gender
