### ISSUE TITLE
Referencing a book/edition/text

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#106]
The usual way of a new entry is like this: Sbd mentions that he has read a book during the long 1970s, which hasn't been existing in our database before, so we include it. 

A very general question I have now:
What is our database about? Is it a text-related database, an edition-related database or an object-related database? It can happen that two people read 野草 by Lu Xun, where it would be impossible to find out which edition they have actually read. In other cases it is often possible to trace the right edition, as there was only one extant before 1979. 
So which use does it actually have to refer to a certain edition, which cannot be representative at all?
The same holds true for the phys. description, as one book could be damaged in Shanghai and undamaged in Shaanxi. And even if we only include the size, say 19x12 cm, would we refer to a certain edition, which leads us back to the paragraph above. 

One concrete example could be 我的大学 by Gorky. We have now filled in "1923" as the date of publication, which relates back to its original publication in Russian. The first hit at nlc.cn for the Chinese edition is 1949, followed by many more editions of this book.

Any opinions?

**Comment by duncdrum** [comment]
This is a core question of your data model. The fact that something is unknown in most cases, is not necessarily a good guide. Instead the research question that your DB is supposed to address should guide what cases your model has to account for and which not. 
If you want your DB to be able to trace a concrete document being read, ripped, and sold by several individuals your model needs to be able to handle individual copies. In this case, something like 

| Pub_date | first_chin_ed | annotation |
| --- | --- | --- |
| unknown | 1949 | original date: 1923 |

If there are no research questions you wish to accommodate dealing with this level of granularity, you deal with texts as abstract entities. But then it doesn't make sense to say that something was written on cigarette paper, because abstract texts aren't written on anything, but float around as concepts.

**Comment by inamoto4** [comment]
For the text file I would say that we are at the level of texts, not editions or objects, which leaves open the question of how to deal with the bibliographic references. 

One proposal:
We may settle on THE FIRST PRC EDITION when referring to the date, place and house of publishing. By doing this we would circumvent the rather useless information à la 80 CE for the Lunheng. So for all our primary sources including imperial and Republican texts, we would only refer to editions between 1949 and 1978 in the field pub_date and the two other related fields. This at least would approximate the respective editions used (as probably the larger part of publications read around 1970 were printed after 1948) and give an idea about the bibliographic details as well. Typically two editions of, let's say, 1951 and 1958 were likely being printed in the same publishing house. Another advantage is that we could effortlessly include the neibu publications, which were often published for the first time around 1960. 
The annotation column is a good idea and the original date can be added, if we are able to trace it easily.
The act file would then still be able to cover the individual dealing of a TEXT. I guess this can make sense, as if one person tore apart 毛主席语录, it was probably because he did not like the text and not because he did not like the edition. 
Even the information that a book (=TEXT in this context) was heavily used, could be included into the act file and serve as a hint that it was welcomed by many people. 

Off the top of my head this would be the most practicable and sound approach for our database.

**Comment by duncdrum** [comment]
>For the text file I would say that we are at the level of texts, **not editions** or objects,
>...
>We may settle on THE FIRST PRC **EDITION**

### ``Text > Edition > Copy``
Maybe I'm not understanding what you are saying, but your proposed solution seems to continue the inconsistency currently in the data repo.  We can certainly record first PRC editions, by making an educated guess that the objects that are destroyed were PRC editions and not antique bamboo manuscripts.  As long as, that is consistent with respect to the dates given in the text file, and its description in the Data-dictionary. 

| type | title | pub_year | note |
| --- | --- | --- | --- |
text | Lunheng | 0080 | |
edition | Lunheng (ZHSJ) | 1967 | an old Chinese text |
copy | Lunheng | 2017 | orig_data: 0080. desc: manual transcription of 1967 ZHSJ ed. medium: toilet paper. |

**Comment by inamoto4** [comment]
When we are at the level of texts, we could - theoretically speaking - as well skip all bibliographic references besides the author and the original date of publication or - as the other extreme - include every edition ever published, as 
1) we usually just do not know which editions our persons have read exactly and
2) even if we would know it, it would not change a thing! 
We might record 20 readers of one TEXT, for whom we all know the exact editions they used. How could we possible include this in our simple model? As our database is modeled, in the end we are assuming that a text is a text and has not been changed over time (although this implicit assumption is obviously very problematic). We record all 20 persons in our person file and refer their reading experience to ONE and the same entry in the text file, i.e. to T0429 (to make something up).

Yet we need a practicable approach for us and our Hiwis. And we have to keep in minds, that our texts on the one hand transcend long time periods and long geographical distances with various languages as well. 
The only editions which we can rely on are the neibu publications, which were often translated for the first and only (for quite a long period at least) time into Chinese and are of great significance to us. So what we really need to have included in our database are the dates of the neibu publications, not necessarily the date of the original publication in Russian, French or Serbian (although this is worth knowing and can be filled into the notes column). To guarantee a relatively consistent approach and focus on CHINESE editions of a certain TIME period, I would propose to make the arbitrary decision of settling for the first PRC edition as the reference standard. By that we would at least approximate the editions which were in use back then and be transparent in our recording. 
 
It might be possible, that some zhiqing in 1975 dragged an edition of the 1930s or 1890s with them, yet I guess that the major part of the publications read at that time were printed after 1945 (so the date could be set to 1945 too, yet due to the very different landscape of publishing houses after 1949 I would actually prefer 1949). By using this approach, we would at least reproduce a LIKELY edition, which was often reprinted in the same publishing house and therefore resembled later editions! We would therefore cover "a textual field", which lacks a concrete form and would yet be consistently captured by us.

We would also see immediately if there even existed a PRC edition (maybe there was none before 1980, so they had definitely read an earlier edition) and usually exclude the editions of the Reform period, as we are looking for the FIRST PRC edition. So for 99% of our texts in the column "First PRC edition", the scope of the editions is limited to the time between 1949/50 and 1978/9, the remaining ones having a date after 1980 or no date at all if the publication was ONLY printed during the imperial and/or republican times.

I hope my intentions became a bit clearer by now. :-)

**Comment by duncdrum** [comment]
Sounds good so ``Text.csv`` records editions, since you need that level of granularity for neibu materials. Information about the text more broadly, or specific copies, needs to go into note columns, since the standard mods fields record editions.
Acts of reading refer to texts, with PRC editions as stand-in (T0001), where acts refer to copies, a note or commentary needs to be added to either ``Text.csv`` or ``Act.csv``.

**Comment by inamoto4** [comment]
Well-summarized, thank you!

With regards to 
"where acts refer to copies, a note or commentary needs to be added to either Text.csv or Act.csv",
I would definitely try to stick to the edition approach in the text table and free it from any references to specific copies/objects, which would be dealt with in the act table.

**Comment by duncdrum** [comment]
I think that this policy change makes the introduction of a secondary sources table more prudent. But I'd welcome some feedback from people with a better overview over all the materials on this. I m also thinking about the sources that are hidden in the person table which will need a new home, do we really care about the first PRC edition of a Nature article from 2010?

**Comment by inamoto4** [comment]
"So for all our primary sources including imperial and Republican texts, we would only refer to editions between 1949 and 1978 in the field pub_date and the two other related fields."

Any sources first published after 1978 should not be checked for their original pub date.

I guess that we have talked about the secondary sources table in Munich already, and your idea was that it is not necessary, if I remember correctly. We have basically two kinds of sources, our primary and the secondary ones, e.g. autobiographies. We can still do an update on this decision, yet I would be curious where you'd see the advantage?

I will update the data dictionary (and the act table #84) tomorrow.

**Comment by duncdrum** [comment]
Yes, back then we had a Text table, that could hold different kinds of sources. with the focus on editions, the distinction between primary and secondary sources becomes more pronounced, so it would be nice if the model reflected that. **If** the distinction is relatively clear in light of our data, then I'd say go for it, otherwise not. We could alternatively think about adding a fixed phrase into the notes or comments field, to highlight secondary sources as such.

**Comment by inamoto4** [comment]
First: I am not totally convinced that we have switched from a text approach to an edition approach. I guess we have had some mixture with a certain orientation towards the object. 

I on the one hand just wanted to have a standardized and accountable way to fill in our data. On the other hand we have these very important neibu editions, which in the proposed way will mostly be covered in their neibu edition, as the neibu editions usually also marked the first translations into the Chinese language. 

But I think of this more of as an important side effect. The point is that we are dealing with texts and that On the Road (neibu) as well as Les Miserables (only venturing a guess: first translated during the Republican era) both had had a huge influence in China and are constantly referred to in our material, no matter the edition! So I think it is reasonable to set an arbitrary limit, within which we record the editions.

For the rest, I am content with your recommendation that we should think again about the best way to distinguish Primary and Secondary Sources. Thanks for bringing this up again, I think it's an important point!

**Comment by duncdrum** [comment]
@inamoto4 since most of the grunt work is done, could you model a secondary source table (including data-dictionary edits) and check the text.csv to make sure it adheres to our approach. keep #138 and #115 in mind.

**Comment by duncdrum** [comment]
@inamoto4 the relevant info is in this thread. `pub_date` captures dates `between 1949 and 1978` by default. This makes sense for the majority of the materials and what we are trying to study, but this means that articles from 2010 sit awkwardly in this table, hence the need for a second table to clean this up.  There will be enough corner cases as is, so lets move the obvious out of the way first. Otherwise we get all kinds of funky artifacts in our analysis were people that died in 1979 are happily reading articles in 2014.

The table structure should follow that of the text table (albeit with fewer columns).

**Comment by inamoto4** [comment]
The relevant info is in the data_dict. 

I think that it is time to fix a Skype call, I would propose sometime next week. In that Lena, you and me may debate some open issues.

**Comment by duncdrum** [comment]
@inamoto4 I think this was dealt with by #204, if so go ahead and close.
