### ISSUE TITLE
missing info in text file

### ISSUE THREAD

**Issue by mira-gruenwald** [LenaHenningsen/ReadingData#117]
@inamoto4 @chiayiwu #106 #116 
I couldn't find the publ. info on some entries in the text file.

Mostly some poems without english title (T00064 - 66 and T00084) and T00057. There are as well some entries I'm not sure about the english title ( T00071/72).

Others are:
T00021, T00050, T00083, T00086. 
For T00070 I couldn't find the novel written by Bi Ruxie. But I found an edition written by Zhibo Chen, published in Beijing: Jiefang junwenyi chubanshe, 1990.

**Comment by inamoto4** [comment]
Thanks a lot again to all of you, the text file looks great! I have only found one problematic entry left, as it does not have a proper source, so I marked the entry red. It is mentioned in Wu Hong. @mira-gruenwald Would be great, if you could complete the entry. Please also take care of the notes in the note column and delete them after that.

Now only some tricky residuals are left.
In our case we have the example of 过秦论 by 贾谊. Mira correctly checked for nlc.cn, did not find it and went on to check worldcat, where she found a rather murky entry with the pub date "1950-1979". Yet we can see two problems here:
It was published in Hongkong by Youlian.
However, solely the publishing houses on the mainland are important to us, as we can rule out the possibility that mainlanders got their hand onto a Taiwanese edition. A HK edition would be a LITTLE more likely, but these ones we would usually not record as well. So Youlian, Taiwan zhonghua shuju, Taiwan shangwu should all be replaced. 
Even more so, the referred text is only a few pages long and was therefore very likely published in a collection of his works. 
So, for single poems, plays or essays, which haven't been published separately, we'll obviously have to come up with a solution. One simple one would be to only give the pinyin. Another one our own translation in [ ]. In both cases we would have to leave the pub details empty. A third possiblity would be to choose an anthology, the quanji or whatever collection we know this piece is in. Yet, do we even know it? Any opinion on this?

Some further remarks:
- Any additions like "ziliao shi" are not needed. 
- "Less than one" unfortunately was a wrong entry by a former student's assistant. Brodsky has published it in English in 1986. When writing prose, Brodsky would occasionally use English, so this should be the original, which did not appear any time before. Be aware that there are other authors under the name Brodsky, which were translated into Chinese and were published before 1966. I guess the first book by Brodsky translated into Chinese was 从彼得堡到斯德哥尔摩  in 1990 (From Saint Petersburg to Stockholm [the place where he was awarded the Nobel prize in 1987]). Yet again, there is no similar book title in the English version, the Chinese probably came up with one on their one.  So all really, really tricky.
- For Akhmatova we have no title. Sometimes only the authors are named without a reference to a specific title. I guess we'll keep the cell empty, although we'll never be able to obtain that piece of information and do not add a NULL?
- We do not need to put sources for our secondary sources!
- I guess that we have to harmonize the serial part as well, right? Any suggestions, also for the data dict?

As the text file is basically cleaned up, I would write another short text of how to proceed from tomorrow onwards with the person file. All step by step! :-)

**Comment by duncdrum** [comment]
@inamote4 might i suggest to split up your comment into actionable items and questions. Otherwise it will be really hard to keep track. Of the top I m against using any special characters like ``{["`` in the title field to signal something. This info needs to made explicit, which we have the comments column for. 
The good news is that the really, really tricky parts are actual the ones with the most research value. I m happy that we are beginning to tackle them. Thats what all this preliminary nitpicking about use of commas and terminology is about.

**Comment by inamoto4** [comment]
Can this be closed?
