### ISSUE TITLE
Translation of so far untranslated texts

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#121]
How do we deal with texts which haven't been translated into

a) any language
b) German
c) French
d) Russian
e) Mongolian 
f) Italian

Please give an answer for all six cases I am referring to.

**Comment by duncdrum** [comment]
check the data dictionary:
>  a) title in Chinese characters; b) title in original language

a) Just Chinese for untranslated text, if you want to add pinyin in just those case we need to adjust the data dictionary.

b - f) You only track original language, where the Chinese edition is itself a translation. If Mr. Wang only read les Miserables in french, there is no chinese edition, if he read it in mongolian original title is french, and translated is mongolian. 

Not sure where this question is going.

**Comment by inamoto4** [comment]
Take this example: 
Bei Dao has written a poem and we usually want to come up with a translation for this text. However, there (only an example!) is no translation of Bei Dao's poems. Yet it might be that Bei Dao's poem has already been translated into German. What in the case of a French, Mongolian or Russian translation (as the only one)? Would we take this into consideration or will we only refer to a English translation in a well-known academic publication? What about (private) webpages?
Chia-yi even translated one on her own. So we do need a consistent approach.

**Comment by duncdrum** [comment]
I would stick with english as it's the language of the database. If there are no published english translations the obvious choice are either pinyin (meh) or translating it our self and pasting a fixed phrase into the comments field, e.g. ``Translation by project member``

**Comment by LenaHenningsen** [comment]
I agree with Duncan: please not pinyin, that is of no help for people who do not read Chinese. So produce a translation, add the comment mentioned by Duncan.

**Comment by inamoto4** [comment]
Alright. @mira-gruenwald 
Could you please confirm by closing the issue?
