### ISSUE TITLE
Publication details to single texts

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#122]
How do we deal with single texts such as the 过秦论 by 贾谊.
It is only 14 pages long and would be usually found in collections. 
The same holds true for specific poems.

1) In case we know for sure that a text appeared in a certain collection: 
Shall we give the pub details for the collection or leave it out completely?

2) If we answer the question above with yes and we are encountering a case, in which we do not know where it had been published: Shall we proactively search for it and if so, for how long?

**Comment by duncdrum** [comment]
1. Obviously we track first PRC editions even if they are collections. 
2. How long is a matter for Lena to decide. When you don't know, you type ``unknown``. This keeps the data consistent, and informative.

**Comment by inamoto4** [comment]
To 1. 
I guess this is the best approach possible too, yet we are referring to a text (过秦论) in the title information and would give the pub details for something totally different like 中国政治思想, in which we could find that work. So we should add the title information in the commentary field, I guess. How so then? In pinyin and Chinese characters?

**Comment by duncdrum** [comment]
No, its like a journal article: the title is that of the essay (hanzi), the publication-info comes from the collection (hanzi), mentioned in the source-id (T0000xx). If the collection doesn't have its own ID yet, it needs to be added to the table with its own id(hanzi). This way we can actually track that people read all those different essays by different authors, but where actually sharing the same book.    
Comments and notes are never the right columns for standard bibliographical data fields.

**Comment by LenaHenningsen** [comment]
Thanks, that sounds like a good solution. 
As to "for how long" - I'd say: do a "quick" search of a couple of minutes, but do not spend hours on that.

**Comment by inamoto4** [comment]
Alright. @mira-gruenwald
Could you please confirm by closing the issue?
