### ISSUE TITLE
Authors without a text

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#123]
For Akhmatova we have no title. Sometimes only the authors are named without a reference to a specific title. I guess we'll keep the cell empty and do not add a NULL, although we'll never be able to obtain that piece of information?

**Comment by duncdrum** [comment]
unknown, null, n.d., all work. If you can make an educated guess at what book by that author it could have been, use the note or comment column

**Comment by inamoto4** [comment]
Okay, I would prefer unknown then. I am going to come up with a consistent approach.

**Comment by duncdrum** [comment]
@mira-gruenwald can you have a look at this and close the issue with your next PR or here on Github if this is already completed.
