### ISSUE TITLE
different page numbers in person-file and old text-file

### ISSUE THREAD

**Issue by mira-gruenwald** [LenaHenningsen/ReadingData#134]
#93 
While copying the source id from the person file to the act file I noticed that sometimes the page numbers are not the same as in the old excel-file.
For example, in the person-file reading acts of P0003 are linked to the source Zhang Langlang 1999: 52. But in the old excel file I can't find any entry related to this page number. Still there are a few related to page number 38 . 
Does Zhang Langlang 1999: 52 refer to an act which hasn't been added to the old file yet?

**Comment by inamoto4** [comment]
I suspect that this is due to a mix-up with another source, namely Zhang Yang. <第二次握手>文字狱, also published in 1999. @LenaHenningsen Could you please confirm this? I guess we do not have that source in a digital version.
