### ISSUE TITLE
Comma in title

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#146]
How do we deal with commas in a title? 
See T00149 探讨(,) 整肃与命运
translated as Explorations(), Rectification and Fate.

Leaving out the comma makes a complete different meaning, already in the original Chinese.

**Comment by duncdrum** [comment]
Full-width comma u002C `，` or ideographic comma u3001 `、`shouldn't be a problem, in the translation use a semicolon.
For these few cases we can think about fixing the translation later on the web-page.
