### ISSUE TITLE
Wu Hong et al

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#149]
Wu Hong has written a very illuminating piece, which I guess we all should take a look at:
https://www.douban.com/group/topic/33998632/

Yet, I think it is not easy to transfer the information into our database model. 
First: There is so much! 

Second: In the old model we have had two extra columns father and mother which we now substituted by Social status. I think that our model is still okay, but if we get to know the family of a person, we might add them into the commentary column. 
We have two or three entries featuring the parents of the persons who are of interest to us. I do not see that this makes sense, as we are not interested in the parents at all. The commentary column might suffice.

Third: Originally we wanted to show networks of people. These relations are recorded in our act table when it comes to discussing or exchanging books. However, more general information such as "he was my friend" or "he told me that the CR is about to come" can't be found in the act_types. How do we deal with that kind of information?

**Comment by duncdrum** [comment]
1.  the more the merrier.
2.  we should not do that. `commentary` should be just that.  We can either add a new column for `social_ties` in person and define these ties in `social_status`, or create two new tables and record them there.
3.  Acts ≠ social networks.  Kinship ties need to be recorded separately from what we have right now.  If we want to record more generic social ties (friend,  co-worker, drinking-buddy) s.a.,  otherwise we can infer from the data we have right now that everybody that shared a book  were `friends` but that is pretty thin evidentiary ice.

**Comment by LenaHenningsen** [comment]
2. you are right with the more the merrier - but for so many people we do not have the info about parents at hand and it will just cost too much time to search for it. 
3. So far, this "he was / is my friend." has not been recorded - for some people we just know this or can easily infer it, but it would mean missing much info, so I'd rather not go into this, but focus on interactions with texts/books - which often means interactions with people, too, of course.

**Comment by duncdrum** [comment]
@LenaHenningsen fair enough. With an eye to future expansions,  we can of course not spend time looking the information up, but provide a place and the means to record it in the database regardless.  This seems like the kind of thing that is bound to pop up in the future.

**Comment by inamoto4** [comment]
I think that by now it is very important that we get our structure right and complete and be clear about our direction, so that we can fill in information we find. I recently encountered online several 回忆, where names of books and people were given in full detail and the way they travelled. When we started the database, we said that in the end we want to display these travellings with Gephi. For that it would be very important to give as much information about the people as we can, as all of these travellings of ideas were defined by personal connections and spatial aspects. 

It is also important where we might end up numerically speaking in our person file. Inferring from what we have read so far and putting in some extra guesswork, I would come to the following estimation:
We basically have two layers of people who are writing autobiographies:
High-brow intellectuals and their peers, who influenced the course of Modern Chinese Intellectual history a lot. Most of them have written their autobiographies in Chinese and many are still meeting today, as we find a lot of pictures of them from recent years. The book project Qishi niandai is another example. 

This core group might have the size of 500-1000 people. No one of them was a standalone artist, they had to operate within groups as they were bound to the countryside, needed intellectual exchange and had to share the few resources (brushes, books, instruments) they could lay their hand on. The resources they had available were predefined by their family background. The time and direction of their return from the countryside was defined by the guanxi of their family as well. As they are so famous and well connected, we can get a lot of information to each of them. 

Then there is the much bigger number, who was not famous but just part of the 16 million zhiqing. Some of them have capitalized on their experience by writing books dedicated to the American or European market, usually in the English language. Relevant information in these books is often sparse.
I assume that we would still have a way bigger number of rather unknown people who have published sth in Chinese. Xujun Eberlein's homepage might be one example, although it seems to be a mixture of the first and second group and I am not sure of how the contributors to Remembrance are chosen. Just to give a very rough idea, I would guess that this 2nd group could contain sth between 5000-10000 people. The chance is slimmer that people who belong to this group have connections to famous intellectuals or politicians. 

(Btw, I would also assume that we have a clear gender gap in these two groups. The autobiographical writing of high-brow intellectuals we came across was mainly done by men, probably >80%. I guess that we have a distinct gender imbalance in the zhiqing group as such, as more boys had received higher schooling during the 1960s than girls. Yet, in the 2nd group the imbalance should not be that crass.) 

It is now for me the question of how we want to proceed. If we want to record the biggest possible number of books, we are probably right to record a high quantity of texts. If we really want to establish a network of ideas and people, I think that it would be important to work more in a qualitative direction, continue working on the entries we already have and create an extra file for family members each. 

We somehow have the network idea by the inclusion of their 下乡地点. Yet there are three problems with it: Many of the well-connected people returned already by 1972/73, so we would miss about the latter part of the CR. Even during the early period they had different opportunities to exchange ideas and goods: 
1) In the very beginning of the CR, as the schools were closed, they just stayed home and dawdled away their time. They were sent to the countryside only by 1968/69. They had amply time to meet.
2) Later, they returned home about once a year for the Spring festival. 
3) They wrote letters! 

Due to this train of thought, I would also opt for the inclusion of friends and acquaintances. However, it should be possible to record circles of friends. If somebody enumerates ten important people who were constantly hanging out with each other, this should somehow pop up in our database. And as a more general statement, I would also opt for some more qualitative work on the people we have already recorded. It would also mean that we have to favor certain data sets over others, as we could not treat these data equally with the amount of resources we have by now.

To conclude: I think that it is pretty hard to separate the travelling of ideas from the people.

**Comment by duncdrum** [comment]
@inamoto4 As usual good points. Leaving interpersonal relations out of the model makes generating networks indeed tricky. To be blunt: No links, no network.

I have the feeling that our discussion is mixing up data-model and data-input. Not all data-input has to be manually. We are only converting the old excel stuff manually now, because that data is not machine-readable. Future addition could well use automated tagging to read the data for 1000 persons, or texts. It therefore makes sense to include relevant entities, such as personal relations, in our model for which there is very little data to date, or where we don't have the time to fill it in manually. 

The numbers Olliver mentions are only big in light of manual input and typing. They are far from reaching any limits of the database or data-model. As for the circles of friends, this is not an issues. It requires that the relationship between each member is stored in the database, its called a clique in SNA terms.

**Comment by duncdrum** [comment]
@LenaHenningsen we should discuss this maybe on skype, but the bottom line stands: Do we really want a database that does not contain *any* data about interpersonal relationships?
In case we don't, we need to model a new table (see my example above), create the data-dictionary entries, and edit the wiki.

**Comment by inamoto4** [comment]
I will talk with Lena about it today in person.

**Comment by duncdrum** [comment]
After the skype call personal relations are coming this ticket is superseded by #153 and #170
