### ISSUE TITLE
Invalid dates in person.csv

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#151]
Welcome on board Wenxin. I have a good starter task for you. As explained in [the wiki](https://github.com/LenaHenningsen/ReadingData/wiki/FAQ),  we use EDTF (soon to be part of iso standard *yay*). Some dates in the person table don't adhere to this (mostly in `birthyear` and `deathyear`), e.g.: `772`, `1954 or 1934`, … . 

@BIGBUNNIEEEE please correct **all** the dates in the `person.csv` to be valid iso-dates. (See the document mentioned in the wiki to see what the right notation should be). Once you are done, create PR that closes this issue via its comments field.

**Comment by HUANG0421** [comment]
Hello, I've handed in the pull request. Actually I got in contact with Frau Henningsen already, because that account @BIGBUNNIEEEE  never looks professional. Now I change a new account called @HUANG0421, and hoping to get the understanding.

**Comment by inamoto4** [comment]
To take over once the role of Duncan:
Do not close it manually, close it with a Pull Request.
