### ISSUE TITLE
Kinship classifiers

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#153]
If we are going for a separate table for relationship, or even two: one for kinship, and one for social liasons. We should think about how to capture these relations, this is typically tricky stuff here is an article to get us started (just skip to the appendix to see how they do it):
[Chinese Kinship Semantic Structure and Annotation Scheme](http://ucrel.lancs.ac.uk/publications/CL2007/paper/63_Paper.pdf)

related to #149

**Comment by LenaHenningsen** [comment]
Thanks for this - sounds to me like we rather not go into this business.
Lena

**Comment by inamoto4** [comment]
I think that kinship relations are a central part of our database. Duncan has proposed the following form:

|ego|relative|relation|rel_zh|rel_en|source|note|created|created_by|last_modified|modified_by|
|---|---|---|---|---|---|---|---|---|---|---|
| P0003 | P0170 |S4.1.1m|父亲|father|…|…|…|…|…|…|

In this way we are open to capture all kinds of kinship relations. Yet I see three little challenges.
1) Who are we going to include and who not? We could do this by a standard procedure, i.e. every brother, sister or father and mother OR only if it is relevant to our research interests. I would at least like to include every father and mother, siblings and grandfathers only if it seems important. How about the spouses though?

2) For the description of kinship relations we have a very fine-grained taxonomy in the Chinese language. This is different for European languages. As we are dealing with Chinese as well as English texts, we might encounter the case that it only says "Sister". It wouldn't be even possible to translate that into Chinese. The other way round might be complicated as well, for example in the case of 表哥.

3) We are obliged to include every person mentioned in our database with an own entry, right? In case we only have the name of the sister we just put that name, correct? How about if not even the name of the sister is given, as she is only named by "my sister"?

I assume that these are hurdles one may overcome. As soon as we have come to a conclusion I would propose that we start a new table, and I would write the relating data_dict entries.

**Comment by duncdrum** [comment]
1. The primary goal is to formalise the information that we have. Not to research all known family members. Limit research new information to cases where what is in xlsx now, is insufficient (ie missing family name, or first name, or … )
2. I d follow the simple version of the taxonomy in the OP. `姐姐` = `sister`, `妹妹`= `sister` IMV `paternal affiliate uncle` is just cluttering up the `rel_en` field, thats why we have `relation` for more specificity. The english term `sister` is covered by the base taxonomy, the one in the OP is extending to cover Chinese relationship terms. 
3. yes, every person mentioned anywhere in the db needs to be in the person table. Anonymous siblings are no different from other anonymous persons, thats what `P0999` is for.

**Comment by LenaHenningsen** [comment]
Thank you, I think I kind of understand that.

Spouses, I think, are not so relevant in this case, as the zhiqing in most cases were still unmarried. (Which is not to say that spouses in general are irrelevant.)

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: LenaHenningsen/ReadingData <reply@reply.github.com>
Datum: Montag, 22. Januar 2018 um 19:53
An: LenaHenningsen/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Comment <comment@noreply.github.com>
Betreff: Re: [LenaHenningsen/ReadingData] Kinship classifiers (#153)

 
The primary goal is to formalise the information that we have. Not to research all known family members. Limit research new information to cases where what is in xlsx now, is insufficient (ie missing family name, or first name, or … )
I d follow the simple version of the taxonomy in the OP. 姐姐 = sister, 妹妹= sister IMV paternal affiliate uncle is just cluttering up the rel_en field, thats why we have relation for more specificity. The english term sister is covered by the base taxonomy, the one in the OP is extending to cover Chinese relationship terms.
yes, every person mentioned anywhere in the db needs to be in the person table. Anonymous siblings are no different from other anonymous persons, thats what P0999 is for.
