### ISSUE TITLE
Link to Qishi niandai

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#155]
There is a little problem with articles from the collected volume Qishi niandai. For some of them it reads reads as if they would be publications in their own right, as there is no link in source_ID. Sometimes we have a direct link to T0044 for the articles from Qishi niandai, as if Qishi niandai would be a monography. We have to come with a consistent approach. I guess we have to take every article from a collected volume separately in our database, right?

Would be great if Duncan could confirm that and Mira then harmonize the respective entries accordingly.

**Comment by duncdrum** [comment]
The latter is the correct approach for an edited volume,  i.e. treat it like a journal with individual articles.
