### ISSUE TITLE
text and related fun materials

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#165]
I think we are still stuck with the contents of the old text table, and how to model it. Let's try something. Forget everything else, and start from a blank page. AFAIK, the old data set contains: 
*  works that aren't text (e.g. music),  see #59
*  textual documents circulating during the CR, see #149, #106 
*  non CR related texts (e.g. secondary sources)
*  quotations #115

Can you make data-model for these including any that I might have missed? So we can see how it looks, and what it would mean for our DB?

**Comment by inamoto4** [comment]
_Secondary sources table_
- We could set up another table for secondary source, although we would then create some other definitional problems. So I am still a bit in doubt. 

_Other artistic works_
- With the current structure, we are not able to model other artistic works, but that was what we said in July already. If we really wanna do that now, we obviously have to change something. What speaks in favor of it is, that our database would allow for more flexibility and could include border cases such as 大字报, posters and calligraphies. In addition, artists of that time were not really separated in pure writers, musicians or painters, many of the zhiqing did everything at once. On the other hand, focusing is usually a good idea, and we already find it hard to control the huge number of sources we have. A textual basis also alleviates certain research problems. 

_Quotations_
- For me, quotations are no texts but acts.

_Data model_
I have set up something which resembles a simple data model. It is not modelled after the data we got, but an estimation of the sources which are out there in the field, although the difference in proportion is not too crass.

For the first image, the thickness of the cursors mark the amount of sources.
For the second image, the size of the box is the marker for the amount of sources.
[Data model.pdf](https://github.com/LenaHenningsen/ReadingData/files/1683386/Data.model.pdf)

Taking everything together, I would say that already by now our csv files enable us to cover the essential aspects of our research project. Nonetheless, I am open to further amendments.

**Comment by inamoto4** [comment]
Edit: I have added fictional works as a possible source for reading practices and put them between primary and secondary sources in the model.

**Comment by duncdrum** [comment]
> Other artistic works

yes in July we agreed to do it later, now is the time. Our problem isn't lack of focus, but that the old (and the current version of the new) text table is trying to do to much at the same time. In db terms there is nothing huge about the number of our sources. 

> Quotations

reading is in act, yet we need a text table to track the object of the readingact. Same for quotations, they can be traceable, or not, or even verifiably false. Yet, they circulate just as texts do. To shoehorn the connection of a quote to its source into `Act` makes no sense, just as it doesn't for readings. To not loose the connection, quotations need their own table (since we ruled out dropping them). 

> Secondary
 create some other definitional problems

could you be more specific on those? There are things being read during the CR,  and things about Reading. If meta-reading happens,  its a primary source.  Anything published after the CR cannot possible have been read during the CR.  Seems a reasonably good starting point to me.            

something along these lines:
![readingdata](https://user-images.githubusercontent.com/6205362/35671746-a77633ae-073c-11e8-835d-ea29dfd891a0.png)

**Comment by inamoto4** [comment]
> In db terms there is nothing huge about the number of our sources. 
Only in terms of (wo)manpower and research focus, that's true.

> Quotations
I see quotations as derivatives from and performances of texts, so it makes sense to me to link them to the texts. The quotations are usually very short, so they fit easily into the commentary cell of the act file. However, I am not against opening another table for quotations.

> Secondary Sources
> There are things being read during the CR, and things about Reading.
What would be your way to distinguish primary and secondary sources? Is it the year 1976? Are autobiographies from after the CR primary sources? I have modeled them as secondary sources, but is that really so? What about an autobiography which was written during the CR? 
What about an commented bibliography of important books which was compiled in 1974 and one which was compiled in 1978? 

To put it more generally:
I guess that one aim of our research project is to show that there are no strict boundaries between author and reader. Authors are readers and readers are authors. Readers performed texts in various ways, when they have talked, sung, or written about or even rewritten them. 
Another assumption of the project is that there are no clear boundaries between the "10 years of chaos" and the time before and thereafter.  I am therefore struggling to clearly identify and separate texts according to their form or time of creation or publication.
If we have one rather bibliographical text file, we do not have to decide that.  

> tertiary 
Databases, bibliographies and simple lists of books, which are typically not edited by a single person, can be understood as tertiary sources. What we are doing here might be such a thing, and a few people before us have tried the same, although way less systematically. It is however not too important to have that in the model.

**Comment by duncdrum** [comment]
> However, I am not against opening another table for quotations.

Good then we have that question settled

 > What would be your way to distinguish primary and secondary sources?

In his recently published Autobiography *My Life* Mr. x talks about reading Sartre in 1970. -> (Sartre) Primary, *My Life* secondary.

The act determines primary. It is the most restrictive category, only stuff we have direct evidence of being read by someone goes in here. Primary requires more research effort, compared to secondary. It's not determined by genre or time (s.b.), but by what is actually in the materials that we have.  

> there are no strict boundaries between author and reader […]

while I don't see what this has to do with `Text`, both `Person` and `Act` have separate entries for reading and writing. Without them the data could not demonstrate anything pro or contra this view. 

> there are no clear boundaries between the "10 years of chaos" and the time before and thereafter

In the other thread we used 1978 as a endpoint, I don't care if 74 or 78 or none, as long as we make our assumptions explicit and remain consistent. If for the purposes of this project there is an end to the CR, then everything published afterwards, is not part of reading during the CR (irrespective of genre). Even if we are to let go of all date restrictions (more work), the difference between titles where we have direct evidence of people reading them, and titles that tell us about what people read remains. 

> Tertiary …  It is however not too important to have that in the model.
Multiple authors are nothing special, imv. Let's not do tertiary then.
