### ISSUE TITLE
Selected works

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#171]
How do we deal with Selected Works of an author, especially if he or she writes all kinds of different texts?
Shall we add another Genre called "Selected Works" and no Genre_type?

**Comment by duncdrum** [comment]
not sure what you mean by how do we deal with? in what context? adding a genre is fine imv, if someone reads the poem "Ode to Books" in *Duncan Paterson -Selected Works* we have a serial for DPSW, and a poem with a title. So two entries just like in a regular bibliography,

**Comment by inamoto4** [comment]
In 1971 my best buddy gave me to read _Duncan Paterson - Selected Works_. 

Under which genre would I subsume this, say Duncan liked to write fictional essays, poems, political essays and a drama once in a while?

**Comment by duncdrum** [comment]
Well the genre of the books would still be `miscellanea` or `selected works`, unless its `selected poems` then its `poetry`.
anything that you can find in here is fair game. http://id.loc.gov/authorities/classification.html
