### ISSUE TITLE
trsl by pm

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#175]
When we say that the note field is reserved for internal communication only, and we put the information "Translated by project member" into that field, we say that this piece of information should not be seen by the outer world, right? In a way I think this is a little wrong.

**Comment by duncdrum** [comment]
I know what you mean, but once we are done with developing and actually releasing the whole monty, we will clean up the notes field. Everything that is defined and mentioned in the data dictionary will stay.

**Comment by inamoto4** [comment]
I guess that the commentary column might be more suitable.

**Comment by duncdrum** [comment]
Not sure what I was thinking, you are correct these should be commentaries not notes
