### ISSUE TITLE
Link collection

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#179]
In case we find something interesting and did not have time to read it, we can first store it in a separate file. I have therefore uploaded a simple Word file in Dropbox. Feel free to change the format, but it is useful to have a handy format for that. This is important as well for cases, where we have already filled in two sources in our database in the person file. 

It also relates to the fact, that we might systematically sketch out which sources we have read so far and which ones we are about to analyze in the upcoming future. 

see #176

**Comment by duncdrum** [comment]
since this file is part of the ongoing work on the DB. I would strongly suggest to incorporate it into the source table when splitting `Text`.

**Comment by inamoto4** [comment]
No double structures, good idea. 

Now we should have the time for it. 
@mira-gruenwald 
Pls go for it!
