### ISSUE TITLE
Adding quotations to our database

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#181]
I am against it. Quotations only cause problems and do not carry a high yield.

**Comment by duncdrum** [comment]
as far as I know we already have quotations in the DB (darwin came up a while ago). I think they can provide valuable insights, but if you don't want them in the db we need to clean up (delete) the ones that are already in.

**Comment by inamoto4** [comment]
I think there is one or zero quotations in the database so far. So it is just a matter of principle which we should decide upon.

**Comment by LenaHenningsen** [comment]
Well if someone quotes a text to someone else in the CR it is relevant. If he/she says this experience was just like in a book, just the same. 
If it is a quote DEFINITIVELY attributed at hindsight, it really does not matter
(It matters because quotations were everywhere and because people were trained to read fiction etc. in order to emulate it)

**Comment by inamoto4** [comment]
This would be an act, Person X tells Person Y about book Z, right? And in the commentary we could add the specific quote, if necessary. 

Quotations are therefore no texts.

But for now we still have them in the old Excel text file. 

Engels | Friedrich | 1820-1895 | 恩格斯 | Germany |   | "痛苦中最高尚的，最强烈的"… | quotation | Zhang Yang 1999:61 | also used as motto to the   shouchaoben The Second Handshake: TSH [1974]_3; Zhang 1999: 61; (TSH   [1974]_2; | LH | Zhang Yang | ca. 1964 | explains what the quotation means   to him

How should we at best include this entry into the act file? I guess we need another Act_type for that?! What does AT06 "to plan to edit texts / quotations by" in this context?

**Comment by duncdrum** [comment]
- ActTyp `to quote` can take both books or persons as objects. If we want to retain the contents of what was quoted we need an edition to point to in the `Text`. The contents of the quote indeed needs to be someplace else, preferably in its own table
- the description of the act isn't clear, did name a manuscript using a quote, did he take this as his motto, who is he, and what is the quote?
- ActType `to explain` makes a lot of sense

**Comment by LenaHenningsen** [comment]
Engels | Friedrich | 1820-1895 | 恩格斯 | Germany |   | "痛苦中最高尚的，最强烈的"… | quotation | Zhang Yang 1999:61 | also used as motto to the shouchaoben The Second Handshake: TSH [1974]_3; Zhang 1999: 61; (TSH [1974]_2; | LH | Zhang Yang | ca. 1964 | explains what the quotation means to him

How should we at best include this entry into the act file? I guess we need another Act_type for that?! 

How about: quote verbatim? 

(Then we can differentiate whether the autobiography says: Oliver quoted Engels – and Oliver exclaimed: “To say it with Engels: ‘The greatest sorrow on Earth…’ ”)

 

What does AT06 "to plan to edit texts / quotations by" in this context?

— AT06: the guy writes in his texts that at the time he was planning to edit the quotations of the person her refers to. (That he probably never did, doesn’t matter, but to me it indicates quite an interest in the texts!)

**Comment by duncdrum** [comment]
I like two ActTypes `to quote` and `to quote verbatim`.

**Comment by inamoto4** [comment]
[Research results sample - texts (books, movies, songs...) February 2017ff (1).xlsx](https://github.com/LenaHenningsen/ReadingData/files/1670245/Research.results.sample.-.texts.books.movies.songs.February.2017ff.1.xlsx)

This is the old Excel file, at least one version of it. ;-)

**Comment by duncdrum** [comment]
Sorry what results should I be looking at?

**Comment by inamoto4** [comment]
You asked about the entry of Friedrich Engels. I have only copied it from that linked Excel file.

**Comment by duncdrum** [comment]
Here is what I would do.
In excel:
-  filter`quotation`, 
-  copy entries to a new file, 
   -  create quote_id
   -  use function to fill the column with the name of who is quoting 
   -  compare with`Person` to get the person_id and identify missing persons
   -  compare new list with `Text` to get the `text_id` of quotations that were incorrectly added to the database, 

in csv:
-  replace occurrences of the text_id to point to the new quote_id, 
-  delete wrong entries in `Text`, 
-  Add quotations to `Act` using just created `quote_id` as object and `person_id` as source
    -  add ActType where necessary
    -  open issue about / edit note  / or add  missing persons in `Person`
 
(the final step depends on how you plan to solve #165)
-  open issue about / edit note / or add missing editions that contain the quoted passages in either `Text`, or `Source`.
