### ISSUE TITLE
Genre

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#192]
Genres need a review in light of their hierarchy and external authority. 
This depends on #165 and #106. 
We could then take a second look at genre's cameo in `Act.source_status`
see #167

**Comment by duncdrum** [comment]
As discussed during out meet-up. `Genre` (and `ArtForm`) need a do-over. For the external authority this means we need to:
-  add  source links to [subject-headings](http://id.loc.gov/authorities/subjects.html) for genrea and [AAT](https://www.getty.edu/research/tools/vocabularies/aat/index.html) for artistic expressions where we can't find a genre term. 
-  make sure we use descriptive names that match the options (incl. alternatives) provided in the previous step

As for our two-level hierarchy, we need to find parent terms that cover `fiction | non-fiction` and something approaching `direct | indirect` reports or observations. The latter will requires some research. We might end up with a three-tier hierarchy:
-  add parents terms as standalone entries (with parent empty)
-  adopt data-dictionary (include URL and prose)
-  change  `Act.source_status` data to be in line with the new hotness

**Comment by mira-gruenwald** [comment]
What about the classification of the sources discussed in #174 ?
01 Academic Sources
02 Life-writing
03 Fiction

As parent terms that cover fiction /non-fiction I would suggest literary and non-literary texts. Literary texts would cover fiction and life-writing. Non-literary texts cover academic writing or other non-fictional texts.

I'm not sure how to include this in the Genre-file as standalone entries...Should there be a new column for the new hierarchy or do we change the genre_type for that?

**Comment by duncdrum** [comment]
@mira-gruenwald is this actually based on library of congress subject headings? My understanding is that we want to be able to differentiate between literary and non-literary autobiographies if we can find suitable genres in LCSH then we won't need another column, and can just move up and down their hierarchy. Otherwise we would need a L1 for more generic and L2 for more specific genre types.
