### ISSUE TITLE
Institution and Membership

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#193]
Oliver started with cleaning up `Institution.` We need to finish what he started, the changes are in the membership branch. 
see #167

**Comment by mira-gruenwald** [comment]
I have questions regarding the member_id column in the institution-file: Do we add various members to this file? Should there be more columns then, or are the members of the institutions already included in the membership-file?

**Comment by duncdrum** [comment]
In the membership branch Oliver has already refactored the column into its own table IIRC. So there shouldn't be `Institution.member_id`, but you are free to propose a different approach.
