### ISSUE TITLE
Act Type: To be influenced by

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#195]
There were many huipishu, which presented other possible forms of Marxism or warned their readers of Communism/Totalitarianism in general and deeply influenced the intellectual youth. I would not say that they took those books as a guide, but they functioned as an eye-opener and made them sceptical of Maoist propaganda. Shall we broaden the G004? Or shall we define another Act Type?

**Comment by duncdrum** [comment]
Yes things i disagree with can influence me, because I don't take them as a guide. Another actType is the way to go here.
