### ISSUE TITLE
Source status

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#200]
In the act file we got a column called source status. In it we can choose between 

01 Academic Sources
02 Life-writing
03 Fiction

In my understanding this is a bit superfluous. When we link the source via the text file, we already have this kind of information. So I guess that there would be other ways to show that, as we could also group the different genres we have into one of the three above-mentioned categories and display the source_status automatically. 

So, I would be grateful for any explanation. :-)

**Comment by duncdrum** [comment]
see #192
