### ISSUE TITLE
Han Dongping 2008:93

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#206]
I have checked the above-mentioned source from the old Excel file, but in my edition page 93 only has a picture, no written information. I am referring to the source text for the entry on Gao Yubao 高玉宝: 我要读书. 

@mira-gruenwald Could you please check again?

**Comment by mira-gruenwald** [comment]
I checked the page again and in the edition here in Freiburg (NY: Monthly Review Press, 2008) it's page number 93.
