### ISSUE TITLE
Genre for Quotations?

### ISSUE THREAD

**Issue by mira-gruenwald** [LenaHenningsen/ReadingData#219]
Quotations are listed as Genre in Library of Congress : http://id.loc.gov/authorities/genreForms/gf2014026159.html

Should we include it in the Genre and Quotation-file ?

see #192

**Comment by duncdrum** [comment]
Including a the link in the data dictionary for `Quotation` would be useful, no need to repeat the info for every entry in the actual table. No need not to put it in genre as well then, who knows if and when we ll need it.
