### ISSUE TITLE
P0030 Dong Shabei

### ISSUE THREAD

**Issue by HUANG0421** [LenaHenningsen/ReadingData#223]
I'm working on the Excel-File, and at the work _Inauguration of the State_, as what a i found on the internet, it's author was not P0030 Dong Shabei, but his Father Dong Xiwen (https://en.wikipedia.org/wiki/Dong_Xiwen).
Should I take this person and add new files? :-)

**Comment by HUANG0421** [comment]
I read the source text(SS00238) again, and I saw there are two paintings name Inauguration of the State. The one from Dong Shabei is his copy of his father's. Should I make two files at ArtWork? 
P.S. Which the author (P0011) from source text mentioned is from Dong Shabei.

**Comment by duncdrum** [comment]
Yes, two entries makes sense if there are two artworks.
