### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by damianodamiani** [LenaHenningsen/ReadingData#227]
hey everyone, two minor issues: 

- I just created a new branch (importing 'S') but it's labeled as created by @duncdrum and two days ago (see screenshot). Why is that so?
![screen shot 2018-04-13 at 14 37 26](https://user-images.githubusercontent.com/35594124/38735146-3e5213ce-3f28-11e8-9d67-4fa97a415b93.png)

- @mira-gruenwald changed the title of her branch a few days ago to "Addition of entries from Tagore to Twain", yet the branch is still titled as before (see screenshot). Why is that so?
![screen shot 2018-04-13 at 14 37 32](https://user-images.githubusercontent.com/35594124/38735153-424465ea-3f28-11e8-9f31-19269a360da8.png)

**Comment by duncdrum** [comment]
the screenshot says **updated** by my, because i made the last commit in this branch by merging miras changes. 
renaming branches after they were created can take some, or more often only happens locally until some action is taken in the main repo, nothing to worry about.
