### ISSUE TITLE
Add new ActType?

### ISSUE THREAD

**Issue by HUANG0421** [LenaHenningsen/ReadingData#228]
I have here a question about the ActType:

Lin Da wrote (2010): _1970年，法国文学翻译家袁树仁还是32岁的年轻人，他去北京图书馆借书。“法文书的卡片已经过筛选，许多‘封资修’著作被拿掉了。填了一个条《茶花女》。工作人员接过去一看，立即厉声斥责‘为什么要看这种作品？’把条给撕了。”_ , it means "He went to the library, tried to borrow the book but didn't succeed". 

Should I add a new ActType for that? Such as: to borrow but not succeed?

**Comment by duncdrum** [comment]
@HUANG0421 yes that kind of information is very interesting, I don't have a good verb for the ActType yet so I m open for suggestions. 
`to be block from reading`, `to fail to obtain`, …

**Comment by HUANG0421** [comment]
@duncdrum I think  >to be block from reading<  fits better. :-) thank you!
