### ISSUE TITLE
New ActType?

### ISSUE THREAD

**Issue by damianodamiani** [LenaHenningsen/ReadingData#244]
what's everybody's opinion on creating a new ActType: AT25 "to watch" (e.g. a movie)?

**Comment by duncdrum** [comment]
If we have information about movies go for it, i would stick with one AT for watching movies, plays, …

**Comment by damianodamiani** [comment]
yeah, I am looking at some sources that mention watching movies. So I'm adding "AT25 to watch (e.g movie or play)."
