### ISSUE TITLE
comma etc. in data dictionary

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#25]
Am I right to suppose, that we are not using , ; : and "blablabla" in the data dictionary?

**Comment by duncdrum** [comment]
yes i would avoid ``,`` but the other ones are ok.  I ll clean it up once we are done discussing fields, and also make it a bit more concise.

**Comment by duncdrum** [comment]
I'd leave this open until it is actually fixed by a pull-request.

**Comment by duncdrum** [comment]
see ff41483ed316f3d9301798744c86fe2f0b70255c
