### ISSUE TITLE
Error: bad signature fatal: index file corrupt

### ISSUE THREAD

**Issue by mira-gruenwald** [LenaHenningsen/ReadingData#257]
Hey @duncdrum ,

I just had to restart my Pc and after that Github Desktop is showing me this error:

error: bad signature
fatal: index file corrupt

The branch I worked on and the changes I did are gone although I had saved them before the restart. 

Is there any chance to fix this ?

Thank you!

**Comment by duncdrum** [comment]
@mira-gruenwald you should follow [these instructions](https://stackoverflow.com/questions/1115854/how-to-resolve-error-bad-index-fatal-index-file-corrupt-when-using-git#1115956)

in essence type the following into windows command line tool (powershell?)

```
del .git\index
git reset
```
