### ISSUE TITLE
Alexandre Dumas

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#277]
Hi everyone, there are - correctly - 2 Alexandre Dumas' in the Repo. However, La Dame aux Camelia is attributed to both of them, it was authored by the younger one, P0304, please correct.
Thanks, Lena

**Comment by HUANG0421** [comment]
I think so. Should I correct it by my next PR? :)

**Comment by LenaHenningsen** [comment]
Yes please.

LH

 

Von: Wenxin Huang <notifications@github.com>
Antworten an: LenaHenningsen/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 2. August 2018 um 13:41
An: LenaHenningsen/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Author <author@noreply.github.com>
Betreff: Re: [LenaHenningsen/ReadingData] Alexandre Dumas (#277)

 

I think so. Should I correct it by my next PR? :)

**Comment by LenaHenningsen** [comment]
One question, did you delete la dame aux camellias entirely?
