### ISSUE TITLE
How to make Mira part of this?

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#28]
What do I have to do so that Mira can also read all this?

**Comment by duncdrum** [comment]
Everybody can read all this 😄 . If you type here name like this ``@mira-gruenwald`` she also gets an email. The instructions for adding her  as a [collaborator](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/)
hi @mira-gruenwald you can check the [wiki](https://github.com/LenaHenningsen/ReadingData/wiki) for some general remarks. Feel free to edit it.

**Comment by duncdrum** [comment]
superseded by #34
