### ISSUE TITLE
first_chin_edition

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#31]
I have to admit that I do not really know we actually need the column "first_chin_edition"?! For the Western and Chinese classics it is the 1950s or 1960s edition that counts. Do we really wanna learn about the editorial details of 水浒传 or 诗经? Can we easily find out when Victor Hugo was translated into Chinese for the first time? I guess for an academic work we would also not be interested in the first Chinese version, as it would be enough to denote the edition at hand.

**Comment by duncdrum** [comment]
any progress on this?

**Comment by inamoto4** [comment]
I have seen that the entries in the text files are not sound when it comes to dates of origins, so we are already running into problems. In my view we should delete the column without substitution. date of publication means the date of the referred object, nothing else is of greater interest to us.

**Comment by duncdrum** [comment]
according to the data dictionary however ``publication_date, publication_place, …`` refer to place of original publication, so whichever way you decide to go, we need to be consistent here in what it is we are recording.

**Comment by inamoto4** [comment]
Pub_place, Pub_date etc. all refer to one object only. The first chinese edition is an additional information we not necessarily have to fill in.
