### ISSUE TITLE
test Mira Grünwald

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#34]
@mira-gruenwald 
Liebe Frau Grünwald, dies ist ein Test, geben Sie bitte kurz Bescheid, ob Sie das lesen können. Danke
PS Wenn Sie das gelesen haben, können Sie das Ticket / Issue schließen.
Herzlich,
LH

**Comment by mira-gruenwald** [comment]
Liebe Frau Henningsen,
ich kann es lesen. Aber wie schließe ich ein issue?

Liebe Grüße,
Mira Grünwald

**Comment by LenaHenningsen** [comment]
Gut, dann funktioniert das schon mal.

Schließen geht, wenn man online ist, das issue auswählt und dann dort schließt. Probieren Sie es mal, wir lernen ja alle gerade, wie das funktioniert ;)

 

Von: Mira Grünwald [mailto:notifications@github.com] 
Gesendet: Donnerstag, 20. Juli 2017 16:55
An: LenaHenningsen/ReadingData
Cc: LenaHenningsen; Author
Betreff: Re: [LenaHenningsen/ReadingData] test Mira Grünwald (#34)

 

Liebe Frau Henningsen,
ich kann es lesen. Aber wie schließe ich ein issue?

Liebe Grüße,
Mira Grünwald

**Comment by duncdrum** [comment]
@mira-gruenwald Sie können das Ticket von einen Pull-request [schliessen](https://help.github.com/articles/closing-issues-using-keywords/), oder wenn Sie selbst Autorin sind hier im browser.

![screenshot 2017-07-20 17 00 49](https://user-images.githubusercontent.com/6205362/28424131-21829846-6d6d-11e7-9e70-462ceae68695.png)

**Comment by mira-gruenwald** [comment]
Close #34

**Comment by duncdrum** [comment]
@mira-gruenwald ja das ist korrekt.
