### ISSUE TITLE
change without change

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#37]
My desktop says I made changes to a number of files which I do not remember I did (as I committed yesterday). So should I commit or discard?

error: Your local changes to the following files would be overwritten by merge:
	data/Act.csv
	data/Genre.csv
	data/Person.csv
	data/Text.csv
Please commit your changes or stash them before you merge.
Aborting

Also: I just fixed the stuff do the place file but received a massive Fehleranzeige so I discarded it all again - only I cannot check the master file as long as I do not either committ or stash things...

**Comment by LenaHenningsen** [comment]
@duncdrum - hier wäre das Folgende:
My desktop says I made changes to a number of files which I do not remember I did (as I committed yesterday). So should I commit or discard?

error: Your local changes to the following files would be overwritten by merge:
data/Act.csv
data/Genre.csv
data/Person.csv
data/Text.csv
Please commit your changes or stash them before you merge.
Aborting

Also: I just fixed the stuff do the place file but received a massive Fehleranzeige so I discarded it all again - only I cannot check the master file as long as I do not either committ or stash things...

**Comment by duncdrum** [comment]
You should see the changes in the desktop. Do they look like the ones you want? 

If you commit and push we can sort it out later. More info about the options  mentioned in the error message [here](https://stackoverflow.com/questions/15745045/how-do-i-resolve-git-saying-commit-your-changes-or-stash-them-before-you-can-me).

**Comment by LenaHenningsen** [comment]
Thanks, this seems to have worked. And yes, it looked like the stuff I did / wanted

**Comment by LenaHenningsen** [comment]
I just checked the place file - the lines that I changed / corrected are by now duplicated in the file.

**Comment by duncdrum** [comment]
Yes, those are the fixes that Oliver and I did while we skyped. Since you didn't pull those in, before modifying the files, they are now in there as double. Let me clean this up so it can be pulled in.
