### ISSUE TITLE
publication place for online publications

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#42]
Hi @duncdrum @inamoto4 @mira-gruenwald 
I think Oliver brought this up earlier: we need a physical place in the text file. What do we do for online publications? (For our modeling later these texts are not relevant, at least so far - as these are the autobiographical texts and not the texts that people read during the CR). So is it ok to leave that slot empty? Or add one fictional place that we then define as "online source" in the place file? (I would like that option but I guess that this is inacceptable for github purists...
Thanks

**Comment by duncdrum** [comment]
In mods ``<location>``encompasses both``<physicalLocation>`` **and** ``<URI>``. So let's stick with uri in this case. We should clearify in the data dictionary if locations are unknown, are empty or have the value ``unknown``

**Comment by LenaHenningsen** [comment]
Thanks.
Empty means unknown, right?
So I would write "URI" into the respective field (capital letters without "   " of course)

**Comment by duncdrum** [comment]
No, you would paste the Uri of the resource "http://someuri.com"

**Comment by duncdrum** [comment]
I think this is now implemented where it needs to be, time to close
