### ISSUE TITLE
branches...

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#46]
@duncdrum @inamoto4 
Can I continue working in a branch after I posted a pull request?
I made one pull request last night; then opened a new branch this morning as I wanted to continue - I merged the first of the branches now as I cannot remember what I did anyhow, and now I have conflict messages. So: should I rather have worked in the old branch when that was not yet merged? Or should I merge myself (as I did now) if no one else does...

**Comment by LenaHenningsen** [comment]
PS especially so, as I find it really hard to read the conflict message in the browser - in fact, I do not really see how to resolve the issue...
(in the second branch, I added lines that should now come below those I did earlier on).
Anyhow, I'll better not continue today.

**Comment by inamoto4** [comment]
I understood that the general idea is to finish a "project", then pull request and wait for the others to merge the branch or comment on it.

**Comment by LenaHenningsen** [comment]
Yes, but this then means that you cannot continue on other things, as it will inevitably result in conflicts…. 

 

Von: inamoto4 [mailto:notifications@github.com] 
Gesendet: Samstag, 29. Juli 2017 11:49
An: LenaHenningsen/ReadingData
Cc: LenaHenningsen; Author
Betreff: Re: [LenaHenningsen/ReadingData] branches... (#46)

 

I understood that the general idea is to finish a "project", then pull request and wait for the others to merge the branch or comment on it.

**Comment by duncdrum** [comment]
actually conflicts only arise if you start a new branch based from master, while there is an open pull request. But Lena is right, pull request should be merged in quickly. If you opened a pull request, and continue to work before it has been pulled in, simply open a new branch **from** the branch that has an open pull request. If the first pull request goes through unchanged, there will be no conflicts. Otherwaise you ned to fetch the changes from master into your second branch before opening your second pull request.

**Comment by LenaHenningsen** [comment]
DANKE!

 

Von: Duncan Paterson [mailto:notifications@github.com] 
Gesendet: Montag, 31. Juli 2017 09:22
An: LenaHenningsen/ReadingData
Cc: LenaHenningsen; Author
Betreff: Re: [LenaHenningsen/ReadingData] branches... (#46)

 

actually conflicts only arise if you start a new branch based from master, while there is an open pull request. But Lena is right, pull request should be merged in quickly. If you opened a pull request, and continue to work before it has been pulled in, simply open a new branch from the branch that has an open pull request. If the first pull request goes through unchanged, there will be no conflicts. Otherwaise you ned to fetch the changes from master into your second branch before opening your second pull request.
