### ISSUE TITLE
conflict from last PR

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#49]
039eea6075822e128afddf601dd921429b747233 marked conflicts as solved without solving them. The files are ``act.csv`` and ``person.csv``

**Comment by mira-gruenwald** [comment]
Ok, how can this be resolved? Do I have to create a new branch and put the act and person id in the right order?

**Comment by duncdrum** [comment]
see [here](https://help.github.com/articles/resolving-a-merge-conflict-on-github/) for an explanation of the conflict markers which are still in our [files](https://github.com/LenaHenningsen/ReadingData/blob/master/data/Act.csv#L10)

**Comment by mira-gruenwald** [comment]
@duncdrum 
I edited the files on GitHub and deleted the conflict markers. Should I commit the changes directly into the master branch, or start a new pull request?

**Comment by duncdrum** [comment]
a PR would be better, either way i ll take a look once you've uploaded
