### ISSUE TITLE
Adding numbers?

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#50]
@duncdrum 
so would it make sense that we add numbers into all the files once @mira-gruenwald has sorted out the conflicts?
i.e. 
A0001 and those where we have already recorde acts are there, but then add until say A0050 or something?

**Comment by duncdrum** [comment]
I generally prefer that there are no preassigned IDs without contents. That way someone could check out a branch label it ``P0100-P0199`` and then go on holiday. In the meantime others can still add new persons simply using ids greater then ``P0199``. But that's just my preference, if you want to do it differently go ahead.
