### ISSUE TITLE
art, music, performance etc

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#59]
Mira discovered entries on music in this [PR](https://github.com/LenaHenningsen/ReadingData/pull/58). How should these be modelled? While the mods scheme has standardised ways of referencing music, art, etc.  I'm less convinced that we should keep those entries together with actual books in a ``text.csv``. We also need to decide if these entries require a source in the bibliography? I think ``act`` and ``acttype`` can handle entires for listening, viewing, attending, selling tickets, etc.

**Comment by LenaHenningsen** [comment]
I would suggest that we focus on the books now and will do music once we are done with that.

**Comment by inamoto4** [comment]
Me too

**Comment by duncdrum** [comment]
Closed by #204
