### ISSUE TITLE
data dictionary and question on act file

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#63]
@inamoto4 We still have comment + substantial discussion as columns in the act.file; do we want to keep both? I have modified the headings in act. so that they fit with the description in the data dictionary but I am not entirely happy with that.
Please also check the dictionary for a line that I have marked in color.
Thanks, Lena

**Comment by inamoto4** [comment]
It seems that the comment column is not used at all. I guess we originally wanted to have a comment on the substantial discussion, right? Not sure whether this still makes sense.
I cannot find a marked line in the data dictionary though.

**Comment by duncdrum** [comment]
comments is for editors to leave comments ala ``MIRA please check for typos``, substantial discussion contains data that users can read and search for.

**Comment by duncdrum** [comment]
lets move discussion to #84
