### ISSUE TITLE
libre office question

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#64]
@duncdrum, is there a possibility with libreoffice to also mark the first line so that you can always see it (and the colum labels), even though you may be writing in line 10001.
Thanks

**Comment by duncdrum** [comment]
[How to freeze rows](https://help.libreoffice.org/Calc/Freezing_Rows_or_Columns_as_Headers). If this doesn't do the trick, you can also work around the problem by always inputting data in row 2 (and adding new rows underneath) and then simply sort before the final save.  
P.S.: Welcome back :smile:
