### ISSUE TITLE
Act 45

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#65]
@inamoto4, @duncdrum könnt Ihr bitte mal Act 45 ansehen? Im Kommentar steht ja recht ausführlich drinnen, was mit der Übersetzung passierte - macht es Sinn, das nur als translate zu erfassen oder translate und destroyed; oder zwei Acts daraus machen? Was wäre das sauberste?
Danke,
Lena und Chia-yi

**Comment by duncdrum** [comment]
To me the act of translating a text, is not logically connected to the fact that the medium of the finished translation later got destroyed. One talks about the agent's actions (aka act). The other about the agent fate. As such [ \<physicalDescription\>](https://www.loc.gov/standards/mods/userguide/physicaldescription.html) on the text table with a ``note`` about the destruction are more suitable imv. This relates to the question we discussed if text.csv can contain copy level information of specific works, or is limited to general edition data.

**Comment by LenaHenningsen** [comment]
MAybe it should be a second act with the text being the object of destruction by someone else…

 

Von: Duncan Paterson [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. September 2017 14:16
An: LenaHenningsen/ReadingData
Cc: LenaHenningsen; Author
Betreff: Re: [LenaHenningsen/ReadingData] Act 45 (#65)

 

To me the act of translating a text, is not logically connected to the fact that the medium of the finished translation later got destroyed. One talks about the agent's actions (aka act). The other about the agent fate. As such  <https://www.loc.gov/standards/mods/userguide/physicaldescription.html> <physicalDescription> on the text table with a note about the destruction are more suitable imv. This relates to the question we discussed if text.csv can contain copy level information of specific works, or is limited to general edition data.

**Comment by duncdrum** [comment]
Yes, that is possible if we know the destroyer, destroying is an act. However, for most research questions that come to my mind, I would be more interested in inquiring the state of the objects that have / have not been preserved. 
If a reader has recalled destroying a text, we need the destroyed act anyway, so no harm in adding it. But from the agens' perspective I'd strongly suggest adding this kind of information to the description of the work in question.

**Comment by duncdrum** [comment]
superseded by #89, and #90
