### ISSUE TITLE
ActType: no "wrote"?

### ISSUE THREAD

**Issue by chiayiwu** [LenaHenningsen/ReadingData#77]
How come there's no "wrote" in the "ActType"? Not sure if I misunderstood or misseen something...

**Comment by duncdrum** [comment]
good question

**Comment by LenaHenningsen** [comment]
Indeed - I guess we did not require it so far, so please add.
Lena

**Comment by duncdrum** [comment]
@LenaHenningsen we'll close this when a pull request adds the act. This makes it easier for everyone to see what needs to get done 😄
