### ISSUE TITLE
T00077 uncertain '62 edition for 紅樓夢

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#78]
Chia-Yi's comment:
>Cannot find any Hongloumeng published in 1962; but in 1957 and 1982 was published by 人民文学出版社

**Comment by chiayiwu** [comment]
@mira-gruenwald 
I saw your last edit was ten days ago (pretty fresh), do we still use the 1962 version? Or as it is written now the 1949 version? Sorry that I didn't take care of this entry earlier.

**Comment by inamoto4** [comment]
Yes, we now proceed as described in my e-mail and the issues. Only use the first mainland edition from 1949 onwards; if you know the first chinese edition, you can add it, but do not spend too much time on it to gather this piece of information. If you have further information on the original publication date in a foreign country, you can add this to the commentary as well. 

It is very important that we can rely on you checking the issues and continue regularly working on the entries. It would help the workflow if we can be sure to get an answer to these issues here within 3-4 days.

**Comment by chiayiwu** [comment]
I see, thanks for the explanation. I try to keep up with the project,
please assign me when I am needed so I get the email always.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
不含病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Mit freundlichen Grüßen / Best Regards,

Chia-yi Wu

2017-10-25 6:40 GMT+02:00 inamoto4 <notifications@github.com>:

**Comment by inamoto4** [comment]
Dear Chia-yi, the easier way would be, if you just regularly check GitHub.
