### ISSUE TITLE
truncated contents in substantial discussion column  in Act.csv

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#84]
e.g. act01 ends on ``foreign language depar`` going back through the history of the file, i don't think the full sentence was ever in the csv.
see #63 

-   [x] let's make sure that the complete cell contents of the source files is included in the new csv files
    -   [x] since brevity is a virtue let's split these discussions across multiple cells 
-   [x] ensure that data dictionary matches the contents of the act file
-   [x] regardless of commentary, substantial discussion, … we still need a standard notes column where editors can communicate their thoughts ala: ``MIRA | did not find it | etc``

**Comment by inamoto4** [comment]
Maybe I am "standing on the schlauch", but I firstly do not see the connection to #63 and secondly do not recognize the bug. For me it reads "East China Normal University's Foreign Languages Department", or did u correct it? Then I do not understand the logic behind this open issue.

Sorry, after a longish break I guess it will take me two or three days to adapt again.

**Comment by duncdrum** [comment]
I corrected the obvious depar = department, but i don't know if anything else has been cut off from A0001 or any of the other substantial descriptions. It's related to the other issues because it touches upon what should or shouldn't go into this column, which is already too long for its own good :smile:

**Comment by inamoto4** [comment]
Ok, it seems to be the case that we are facing a limit of characters I can enter into one cell. Did not know that! The original entry was longer indeed. You can compare it with old Excel file, I have sent it to you via mail. I guess there is no way to extend the character limit and you would in this case just opt for shorter commentaries?
Notwithstanding, I thought we reached the agreement that the commentary column serves as an additional explanation for the user and does not necessarily be part of an analysis by the software. Therefore these specific entries do not have to be systematic and may reach a certain length.

**Comment by duncdrum** [comment]
The character limit per text cell should be 65535 characters. Not sure where in the pipeline this truncating happens, my guess is the excel datatype isn't properly set. I m ok with splitting the contents of substantial discussions over the two columns, but we still need a note column for editors to make comments on the file while editing. 
@inamoto4 would you mind overseeing the conversion of substantial discussion into the new and shiny form.

**Comment by duncdrum** [comment]
@inamoto4 are all tasks done or does this still need work?
