### ISSUE TITLE
Fix modelling of rustication in person table

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#88]
The person table and the data dictionary are no longer in sync. 
We need to fix this, by adding prose to the data dictionary, and by making sure that all cells in the rustication columns actually implement the data dictionaries description. 
Note that ``NULL`` and ``0`` are not the same. Rustication can have ``yes``, ``no``, or ``NULL``.
There shouldn't be any ``0`` or ``     `` (empty).

**Comment by inamoto4** [comment]
We are on it.

**Comment by inamoto4** [comment]
I have changed the DD accordingly. (Next time again as a pull request...)

**Comment by duncdrum** [comment]
You can also reference the issue your are fixing when pushing to master via the commit message. This really makes it easier to keep track of where things are at.

**Comment by inamoto4** [comment]
#93

**Comment by duncdrum** [comment]
⬆️ thats a forum post, which is nice.

commit messages go with your commits into the box where it says ``description`` or ``commit message``. Your latest commit with a message was ``DD Changes`` the message was ``changes in DD related to the person table``

The relevant section of the wiki is [https://github.com/LenaHenningsen/ReadingData/wiki/03-Sharing-and-Uploading](https://github.com/LenaHenningsen/ReadingData/wiki/03-Sharing-and-Uploading)

**Comment by duncdrum** [comment]
@HUANG0421 Now that you have successfully submitted your first PR, here is an oldy but goody also related to dates. The main goal is to make these cells consistent with our model:
1) the cells for `rustication_start` and `_end` must have one of only three values a `date` (same format as for birthdates), `unknown`, or `NULL` *nothing* else (no `empty`, or `LENA`).  Please make all cells consistent in this respect.
2) Since we know that people were rusticated between 1968 and 1979, we can actually say more then just unknown, i.e. `1968..1979` (obviously if `_start` is `1970`, `_end` would be  `1970..1979`
3) If cells need further research please open an issue for each row were the data needs checking. 
4) You PR should close this issue
5) Please also  check the birthdates once more and replace`unknown` dates with better approximates, e.g. `19XX` or `1XXX`

**Comment by HUANG0421** [comment]
Hello :) I have a question about the correction: Should i also correct the "rustication" cells? If yes, could you please tell me the difference between "no" and "NULL"? For example, when a person wasn't born in that time, should I give it a "no"? But when he or she didn't come from China or had died before this time, should it be a "NULL"? 
And another question: If i found the rustication time from someone, and it is not in the cell yet, but there are already 2 source ids, what should I do? :)
Thank you very much!

**Comment by duncdrum** [comment]
Please update the data-dictionary to be more specific:
`records whether or when a person experienced rustication; write 'NULL' if not provide year for yes`
For some PRC citizens of a certain age (no rustication for primary school kids I suppose) we simply don't know hence `NULL.` Unless we can be sure that `no` based no age, or other circumstances. 
For many non PRC citizens or persons from a different historical period (kongzi) we know that they didn't undergo rustication hence `no`
For people where we know they did, write `yes`
Yes if you find dates please add them, if source_id are filled please open an issue so we can decide if we want to include the source in the future or not.

**Comment by HUANG0421** [comment]
Thanks! But what is the difference between "unknown" and "NULL" regarding time? When should I use them?
If we know that this person had be rusticated, but there is no certain time or year, should it be "unknown" or "Null"? :)

**Comment by inamoto4** [comment]
@HUANG0421 
Please take a look into the data dictionary first. :-)

**Comment by inamoto4** [comment]
"No" applies only for people of that age, who did not go to the countryside, because they have worked in a factory or were thrown into prison (like Zhang Langlang)! 
"NULL" is used for people where it does not apply, i.e Confucius or Goethe.
"Yes" goes without saying.

I have updated the data dict and hope, that it is clearer by now.

**Comment by HUANG0421** [comment]
I got it! And Mira also explained me. I will continue it tonight. :)

**Comment by duncdrum** [comment]
this is now superseded by #201, the two issues should be closed together.

**Comment by duncdrum** [comment]
closed by #202
