### ISSUE TITLE
Add to destroy to act types

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#89]
rework entry act 45

**Comment by chiayiwu** [comment]
close #89
but we don't know "who" destroyed the books, we only know the translator's identity and his work was destroyed by some guy. Do I put simply "destroy" on Act 45? I put "translate" originally.

**Comment by duncdrum** [comment]
No, the Act table records individual acts Mr X destroys Book A, Mr Y destroys, Book B, .... The ActType records the verb, of the action. Since in all these case the act was destruction. So ActType is `` to destroy``. Apparently there were two Acts, one translation, one destruction.

**Comment by duncdrum** [comment]
@inamoto4 this touches upon #106

**Comment by duncdrum** [comment]
Still no actType in master branch, this is why we use the commit hooks and messages to close issues instead of closing them manually on the wepage

**Comment by duncdrum** [comment]
We now have an actType ``AT14``to destroy,  but no corresponding act. 
@inamoto4 Do **not** close this issue unless the complete changes are in the master branch.

**Comment by inamoto4** [comment]
No worries, I did not intend to do so. Which further changes do you want to have? Do you mean the act, which corresponds to "to destroy"?

**Comment by chiayiwu** [comment]
I added it as A00079. (The actor remains blank though)
