### ISSUE TITLE
source_id and page_number in person table...

### ISSUE THREAD

**Issue by duncdrum** [LenaHenningsen/ReadingData#93]
sources are texts at the moment there are none in the person table. 
turns out the page_number entries are actually acts. Sooo, 
-   [ ] refactor page_numbers to the act table
-   [ ] add act types where necessary
-   [x] bring data-dictionary in line with the changes to these fields in the person table
-   [ ] cleanup?

**Comment by inamoto4** [comment]
We are on it.

**Comment by inamoto4** [comment]
Picking up on what Duncan has said, we should now tackle the person table. 
AFTER Chia-yi's changes are pulled in, we will refurbish the person table! When we are done there should be no empty cell whatsoever!
The principle (only in this case!) goes as follows: Whoever has originated an entry, is responsible for completing it! That means, that Lena and I will take of our entries and Chia-yi and Mira take care of theirs. Chia-yi did not create so many, so it should not be a big hassle. 
Please do the changes according to the data dictionary, which I updated today!!!
I cannot guarantee that Lena and I will finish our entries during November, but I will surely tackle mine in December by the latest. 

The abovementioned holds true for all columns except for the source_ID and the related column page_number. For this two I want to kindly ask @mira-gruenwald to take care of those where we already have some information. Say, for Mou Dunbai we do not have any source given, yet for Zhang Langlang we have some information given in the column page_nr. 
This rather bibliographical work will lead to a lot of new entries in the text and personal file respectively.

Before we start, I want to ask only one question: 
1) How do we include several sources to one person? Shall we stick to one main source or allow for two or three sources, which will then lead to another two or four columns?

**Comment by chiayiwu** [comment]
I see, I will spend tomorrow to work on it.

**Comment by LenaHenningsen** [comment]
As a response to @inamoto4 
Before we start, I want to ask only one question:
How do we include several sources to one person? Shall we stick to one main source or allow for two or three sources, which will then lead to another two or four columns?

These are important, so I find four colums ok, even though not elegant...
